ERX:
  0_ENABLE: 1 # ROC2
  1_ENABLE: 1 # ROC2
  2_ENABLE: 1 # ROC5
  3_ENABLE: 1 # ROC5
  4_ENABLE: 1 # ROC4
  5_ENABLE: 1 # ROC1
  6_ENABLE: 1 # ROC1
  7_ENABLE: 1 # ROC4
  8_ENABLE: 1 # ROC3 
  9_ENABLE: 0 # ROC0
  10_ENABLE: 0 # ROC0
  11_ENABLE: 1 # ROC3
  0_INVERT_DATA: 0 
  1_INVERT_DATA: 0
  2_INVERT_DATA: 0 
  3_INVERT_DATA: 0
  4_INVERT_DATA: 0
  5_INVERT_DATA: 0 
  6_INVERT_DATA: 0
  7_INVERT_DATA: 0
  8_INVERT_DATA: 0
  9_INVERT_DATA: 0
  10_INVERT_DATA: 0
  11_INVERT_DATA: 0
ETX:
  0_INVERT_DATA: 0
ELINKPROCESSORS:
  GLOBAL_V_RECONSTRUCT_THRESH: 0 # number of erxs that should have the same 
  GLOBAL_VETO_PASS_FAIL: 0xFFFF # select all of the possible combinations of event status bits (E, HT, EBO, and M) as ok
FORMATTERBUFFER:
  GLOBAL_ACTIVE_ETXS: 1 # only 1 active etx
  GLOBAL_IDLE_PATTERN: 0x1277cc
ROCDAQCTRL:
  GLOBAL_PASS_THRU_MODE: 1
  GLOBAL_MATCH_THRESHOLD: 0
  GLOBAL_ACTIVE_ERXS: 0x9FF 
ALIGNER:
  GLOBAL_FREEZE_OUTPUT_ENABLE: 0 # use this since channels might not be locked
  GLOBAL_FREEZE_OUTPUT_ENABLE_ALL_CHANNELS_LOCKED: 0
