# HcalBackplane with ECON Mezzanine and one HGCROC board
# connected to slot 0
ERX:
  0_ENABLE: 0
  1_ENABLE: 0
  2_ENABLE: 1 # HGCROC0
  3_ENABLE: 1 # HGCROC0
  4_ENABLE: 0
  5_ENABLE: 0
  6_ENABLE: 0 # for a HGCROC board connected in HGCROC1 in backplane
  7_ENABLE: 0 # for a HGCROC board connected in HGCROC1 in backplane
  8_ENABLE: 0
  9_ENABLE: 0
  10_ENABLE: 0
  11_ENABLE: 0
ETX:
  0_INVERT_DATA: 1 # invert data
FORMATTERBUFFER:
  GLOBAL_ACTIVE_ETXS: 1 # only 1 active etx
ROCDAQCTRL:
  GLOBAL_PASS_THRU_MODE: 1 # pass through mode 
  GLOBAL_MATCH_THRESHOLD: 0 # number of eRx that must agree on a Header Word for that word to be considered a Header Word
  GLOBAL_ACTIVE_ERXS: 0x0C # active erx, 2 and 3 from HGCROC0
ELINKPROCESSORS:
  GLOBAL_V_RECONSTRUCT_THRESH: 0 # number of erxs that should have the same EBO for the vertical reconstruction (sums the number of 1s and 0s in the bit values from all 12 eRx) to be successful
  GLOBAL_VETO_PASS_FAIL: 0xFFFF # select all of the possible combinations of event status bits (E, HT, EBO, and M) as acceptable
ALIGNER:
  GLOBAL_FREEZE_OUTPUT_ENABLE: 0 # use this since channels might not be locked
  GLOBAL_FREEZE_OUTPUT_ENABLE_ALL_CHANNELS_LOCKED: 0
