ERX:
  0_ENABLE: 1
  1_ENABLE: 1
  2_ENABLE: 1
  3_ENABLE: 1
  4_ENABLE: 1
  5_ENABLE: 1
  6_ENABLE: 1 
  7_ENABLE: 1 
  8_ENABLE: 1
  9_ENABLE: 1
  10_ENABLE: 1
  11_ENABLE: 1
ETX:
  0_INVERT_DATA: 0 # invert data
ELINKPROCESSORS:
  GLOBAL_V_RECONSTRUCT_THRESH: 0 # number of erxs that should have the same 
  GLOBAL_VETO_PASS_FAIL: 0xFFFF # select all of the possible combinations of event status bits (E, HT, EBO, and M) as ok
FORMATTERBUFFER:
  GLOBAL_ACTIVE_ETXS: 1 # only 1 active etx
  GLOBAL_IDLE_PATTERN: 0x1277cc
ROCDAQCTRL:
  GLOBAL_PASS_THRU_MODE: 1
  GLOBAL_MATCH_THRESHOLD: 0
  GLOBAL_ACTIVE_ERXS: 0xFFF
ALIGNER:
  GLOBAL_FREEZE_OUTPUT_ENABLE: 0 # use this since channels might not be locked
  GLOBAL_FREEZE_OUTPUT_ENABLE_ALL_CHANNELS_LOCKED: 0
