ERX:
  0_ENABLE: 1 # ROC2
  1_ENABLE: 1 # ROC2
  2_ENABLE: 1 # ROC5
  3_ENABLE: 1 # ROC5
  4_ENABLE: 1 # ROC4
  5_ENABLE: 1 # ROC1 (not working on L3)
  6_ENABLE: 1 # ROC1 (not working on L3)
  7_ENABLE: 1 # ROC4
  8_ENABLE: 1 # ROC3
  9_ENABLE: 1 # ROC0
  10_ENABLE: 1 # ROC0
  11_ENABLE: 1 # ROC3
  0_INVERT_DATA: 0 
  1_INVERT_DATA: 0
  2_INVERT_DATA: 0
  3_INVERT_DATA: 0
  4_INVERT_DATA: 0
  5_INVERT_DATA: 0
  6_INVERT_DATA: 0
  7_INVERT_DATA: 0
  8_INVERT_DATA: 0
  9_INVERT_DATA: 0
  10_INVERT_DATA: 0
  11_INVERT_DATA: 0
ETX:
  0_INVERT_DATA: 0
ELINKPROCESSORS:
  GLOBAL_V_RECONSTRUCT_THRESH: 0 #2 # number of erxs that should have the same EBO numbers
  GLOBAL_VETO_PASS_FAIL: 0xFFFF # select all of the possible combinations of event status bits (E, HT, EBO, and M) as ok
  GLOBAL_ERX_MASK_CRC: 0xFFF  # mask CRC issues for all 12 eRx links (bits 0-11)
FORMATTERBUFFER:
  GLOBAL_ACTIVE_ETXS: 1
  GLOBAL_IDLE_PATTERN: 0x1277cc
ROCDAQCTRL:
  GLOBAL_PASS_THRU_MODE: 1
  GLOBAL_MATCH_THRESHOLD: 0 #2 # number of erxs that must agree on a Header Word for that word to be considered a Header Word. 
  GLOBAL_ACTIVE_ERXS: 0xFFF #0xF9F
ALIGNER:
  GLOBAL_FREEZE_OUTPUT_ENABLE: 0 # use this since channels might not be locked
  GLOBAL_FREEZE_OUTPUT_ENABLE_ALL_CHANNELS_LOCKED: 0
