name: build test image

on:
  push:
    paths:
      - '.github/workflows/build-test-image.yml'
      - 'env/**'
    branches:
      - '**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: LDMX-Software/pflib-env

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    matrix:
      hosttype:
        - zcu
        - bittware-host
    steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: date
      run: echo "date=$(date +'%Y.%m.%d')" >> "${GITHUB_OUTPUT}"
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.hosttype }}
        tags: |
          type=sha,
          type=raw,value=${{ steps.date.outputs.date }},enable=${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
          type=raw,value=latest,enable=${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    - uses: actions/checkout@v5
    - uses: docker/build-push-action@v6
      with:
        context: env/
        file: env/Containerfile.${{matrix.hosttype}}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
