name: clang-format
on:
  pull_request:

permissions:
  contents: write

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: get just
      uses: extractions/setup-just@v3
    - name: get denv
      run: |
        curl -s https://tomeichlersmith.github.io/denv/install | sh
        denv check
    - name: format C++ code and commit updates
      run: |
        just init
        just format-cpp
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Apply clang-format --style=Google" || exit 0
        git push

