name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - zcu
          - bittware-host
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: get just
        uses: extractions/setup-just@v3
      - name: get denv
        run: |
          curl -s https://tomeichlersmith.github.io/denv/install | sh
          denv check
      - name: basic compile and run tests
        run: |
          just init ${{ matrix.host }}
          just configure build test
        env:
          PFLIB_CONTAINER=1
